### ISSUE TITLE
Unable to mash this potato in time for Thanksgiving.

### ISSUE THREAD

**Issue by huantianad** [drtshock/Potato#136]
I am able to fork this; however, I need to mash it. I also suggest adding some gravy to go with it.

**Comment by wherkamp** [comment]
@drtshock I am not sure what we are to do with these massive issues. We cannot spoon nor mash potato.

**Comment by huantianad** [comment]
Is it possible to create a chrome or browser extension?

**Comment by wherkamp** [comment]
If we MERGE the potato with a FORK this should be a MASH

**Comment by drtshock** [comment]
it would be an upstream mashed potato 🤔

**Comment by Seshpenguin** [comment]
I wanna eat this potato
