### ISSUE TITLE
What Does This Code Even Do

### ISSUE THREAD

**Issue by OmriOn** [drtshock/Potato#151]
What Does This Code Even Do?, Like Wtf

**Comment by Yochran** [comment]
potat

**Comment by OmriOn** [comment]
Bro tell me wtf does this code do

**Comment by Yochran** [comment]
TATO

**Comment by OmriOn** [comment]
_**WHAT ARE YOU EVEN SAYING**_

**Comment by Yochran** [comment]
POTAPTOAPTOPTOAPTOAPTOPATOPO

**Comment by Marcelektro** [comment]
POTATOTATOTPOT

**Comment by AceKiron** [comment]
All the potato jokes aside, I think it just bakes a virtual potato, it's just a meme.

**Comment by OmriOn** [comment]
ok

**Comment by OmriOn** [comment]
> 
> 
> All the potato jokes aside, I think it just bakes a virtual potato, it's just a meme.

okay, cool

**Comment by OmriOn** [comment]
funny **lm_afo_**

**Comment by OmriOn** [comment]
umm someone close this issue lmao

**Comment by OmriOn** [comment]
Okay Thanks.
