### ISSUE TITLE
My potato didn't turn out well

### ISSUE THREAD

**Issue by TruncatedDinosour** [drtshock/Potato#153]
i dropped my potato:(

**Comment by tbdontop** [comment]
rip

**Comment by TruncatedDinosour** [comment]
:(

**Comment by crxssed7** [comment]
should be fine just wash it

**Comment by TruncatedDinosour** [comment]
it's been here on the floor since april 6th and idk if it's fine, what should i do?

**Comment by Dinty1** [comment]
CPR would be a good place to start

**Comment by TruncatedDinosour** [comment]
ahhh, okay, i'll try

**Comment by TruncatedDinosour** [comment]
uhhh, what do i, it's half alive and its trying to kill me

**Comment by Dinty1** [comment]
Force it through the chipper machine

**Comment by TruncatedDinosour** [comment]
i'm scared, he's asleep with my cat rn, i'm scared to wake him up

**Comment by crxssed7** [comment]
well, did you try washing it?

**Comment by TruncatedDinosour** [comment]
lemme try

**Comment by TruncatedDinosour** [comment]
![image](https://user-images.githubusercontent.com/71613062/121219315-17bd2c80-c873-11eb-9aed-d4e720b502cd.png)

**Comment by TruncatedDinosour** [comment]
![image](https://user-images.githubusercontent.com/71613062/121219372-24da1b80-c873-11eb-967d-66033d895058.png)
WHAT HAPPENED

**Comment by wherkamp** [comment]
Potato necrosis

**Comment by TruncatedDinosour** [comment]
OH NO

**Comment by TruncatedDinosour** [comment]
![image](https://user-images.githubusercontent.com/71613062/121225872-7be2ef00-c879-11eb-89d3-2871b149e926.png)
okay, uhm, i resolved it... kinda, welp, good day.
