### ISSUE TITLE
What the f**ck????

### ISSUE THREAD

**Issue by WolfyRed** [drtshock/Potato#158]
WHAT thE f**CK IS THIS>??~?~?~?~~~~!!!!!1

**Comment by AcaiBerii** [comment]
Please tell me this is satire tomfoolery, for I no longer have patience to deal with low-level beings not understanding the importance of forking potatoes.

**Comment by EthanHindmarsh** [comment]
This is serious business.

**Comment by WolfyRed** [comment]
LOL WHAT
