### ISSUE TITLE
I wanted a baked patato

### ISSUE THREAD

**Issue by seanfrasure** [drtshock/Potato#42]
XD

**Comment by drtshock** [comment]
me to

**Comment by AgentTroll** [comment]
I need you to bake one

**Comment by seanfrasure** [comment]
or in this case 3

**Comment by sfxworks** [comment]
Argh now im hungry again..

**Comment by TheSlimeMan** [comment]
:PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP

**Comment by AgentTroll** [comment]
Please refrain from posting useless messages @TheSlimeMan. Thank you.

**Comment by drtshock** [comment]
aaaaaaaaaaaaaaaaaahhhhhhhhhhhhh

**Comment by AgentTroll** [comment]
Please refrain from posting useless messages @drtshock. Thank you.

**Comment by seanfrasure** [comment]
Sour cream anyone?

**Comment by jkcclemens** [comment]
`new Potato();` should get you a baked potato.
