### ISSUE TITLE
WTF is that?

### ISSUE THREAD

**Issue by BullCheat** [drtshock/Potato#85]
Sorry, what the fuck is that repo?

**Comment by MiniDigger** [comment]
There is a Readme for a reason...

**Comment by BullCheat** [comment]
Yes, I know. I just don't understand, is this a weird dummy project? ^^

**Comment by ronneke1996** [comment]
@BullCheat No, this is a very serious repo about cooking or baking a potatoe. And everybody loves potatoes. So please show some love.

**Comment by BullCheat** [comment]
Oh my gosh, of course I love potatoos !
So no Hello World here, only code for the love of potatoes?

**Comment by ronneke1996** [comment]
That's right :)

**Comment by drtshock** [comment]
Potato
