### ISSUE TITLE
Minify potato slices on build

### ISSUE THREAD

**Issue by kshep92** [drtshock/Potato#96]
Potato slices are too big after build. Consider minification of project assets for thinner slices.

**Comment by nickinnon** [comment]
Looking into it. We should be able to apply some lossless minification for all the resource files. Will submit a PR soon.

**Comment by DoNotSpamPls** [comment]
Resources were losslessly minified a while ago. Fixed?

**Comment by kshep92** [comment]
Confirmed! Closing this issue.
